//
// Generated file, do not edit! Created by nedtool 5.6 from replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg.
//

#ifndef __NETWORKPROJECTVANET__REPLAY__REPLAY_MITIGATION_ECDSA_ECDSAAODVCONTROLPACKETS_M_H
#define __NETWORKPROJECTVANET__REPLAY__REPLAY_MITIGATION_ECDSA_ECDSAAODVCONTROLPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace networkprojectvanet {
namespace replay {
namespace replay_mitigation_ecdsa {

class AodvControlPacket;
class Rreq;
class Rrep;
class Rerr;
class RrepAck;
} // namespace replay_mitigation_ecdsa
} // namespace replay
} // namespace networkprojectvanet


namespace networkprojectvanet {
namespace replay {
namespace replay_mitigation_ecdsa {

/**
 * Enum generated from <tt>replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg:9</tt> by nedtool.
 * <pre>
 * enum AodvControlPacketType
 * {
 *     RREQ = 1;
 *     RREP = 2;
 *     RERR = 3;
 *     RREPACK = 4;
 * }
 * </pre>
 */
enum AodvControlPacketType {
    RREQ = 1,
    RREP = 2,
    RERR = 3,
    RREPACK = 4
};

/**
 * Class generated from <tt>replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg:20</tt> by nedtool.
 * <pre>
 * //
 * // Base class for AODV Control Packets
 * //
 * packet AodvControlPacket
 * {
 *     int packetType \@enum(AodvControlPacketType);
 * }
 * </pre>
 */
class AodvControlPacket : public ::omnetpp::cPacket
{
  protected:
    int packetType = 0;

  private:
    void copy(const AodvControlPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AodvControlPacket&);

  public:
    AodvControlPacket(const char *name=nullptr, short kind=0);
    AodvControlPacket(const AodvControlPacket& other);
    virtual ~AodvControlPacket();
    AodvControlPacket& operator=(const AodvControlPacket& other);
    virtual AodvControlPacket *dup() const override {return new AodvControlPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPacketType() const;
    virtual void setPacketType(int packetType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AodvControlPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AodvControlPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg:28</tt> by nedtool.
 * <pre>
 * //
 * // RREQ with ECDSA fields
 * //
 * packet Rreq extends AodvControlPacket
 * {
 *     packetType = RREQ;
 * 
 *     // AODV standard fields (string per evitare problemi di import)
 *     bool joinFlag = false;
 *     bool repairFlag = false;
 *     bool gratuitousRREPFlag = false;
 *     bool destOnlyFlag = false;
 *     bool unknownSeqNumFlag = false;
 *     unsigned int hopCount = 0;
 *     uint32_t rreqId;
 *     string destAddr;              // L3Address come string
 *     uint32_t destSeqNum;
 *     string originatorAddr;        // L3Address come string
 *     uint32_t originatorSeqNum;
 * 
 *     // ECDSA security fields
 *     string senderId;
 *     uint64_t timestamp;
 *     uint32_t nonce;
 *     string signature;
 * }
 * </pre>
 */
class Rreq : public ::networkprojectvanet::replay::replay_mitigation_ecdsa::AodvControlPacket
{
  protected:
    bool joinFlag = false;
    bool repairFlag = false;
    bool gratuitousRREPFlag = false;
    bool destOnlyFlag = false;
    bool unknownSeqNumFlag = false;
    unsigned int hopCount = 0;
    uint32_t rreqId = 0;
    omnetpp::opp_string destAddr;
    uint32_t destSeqNum = 0;
    omnetpp::opp_string originatorAddr;
    uint32_t originatorSeqNum = 0;
    omnetpp::opp_string senderId;
    uint64_t timestamp = 0;
    uint32_t nonce = 0;
    omnetpp::opp_string signature;

  private:
    void copy(const Rreq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Rreq&);

  public:
    Rreq(const char *name=nullptr, short kind=0);
    Rreq(const Rreq& other);
    virtual ~Rreq();
    Rreq& operator=(const Rreq& other);
    virtual Rreq *dup() const override {return new Rreq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getJoinFlag() const;
    virtual void setJoinFlag(bool joinFlag);
    virtual bool getRepairFlag() const;
    virtual void setRepairFlag(bool repairFlag);
    virtual bool getGratuitousRREPFlag() const;
    virtual void setGratuitousRREPFlag(bool gratuitousRREPFlag);
    virtual bool getDestOnlyFlag() const;
    virtual void setDestOnlyFlag(bool destOnlyFlag);
    virtual bool getUnknownSeqNumFlag() const;
    virtual void setUnknownSeqNumFlag(bool unknownSeqNumFlag);
    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);
    virtual uint32_t getRreqId() const;
    virtual void setRreqId(uint32_t rreqId);
    virtual const char * getDestAddr() const;
    virtual void setDestAddr(const char * destAddr);
    virtual uint32_t getDestSeqNum() const;
    virtual void setDestSeqNum(uint32_t destSeqNum);
    virtual const char * getOriginatorAddr() const;
    virtual void setOriginatorAddr(const char * originatorAddr);
    virtual uint32_t getOriginatorSeqNum() const;
    virtual void setOriginatorSeqNum(uint32_t originatorSeqNum);
    virtual const char * getSenderId() const;
    virtual void setSenderId(const char * senderId);
    virtual uint64_t getTimestamp() const;
    virtual void setTimestamp(uint64_t timestamp);
    virtual uint32_t getNonce() const;
    virtual void setNonce(uint32_t nonce);
    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rreq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rreq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg:55</tt> by nedtool.
 * <pre>
 * //
 * // RREP with ECDSA fields
 * //
 * packet Rrep extends AodvControlPacket
 * {
 *     packetType = RREP;
 * 
 *     // AODV standard fields
 *     bool repairFlag = false;
 *     bool ackRequiredFlag = false;
 *     unsigned int prefixSize = 0;
 *     unsigned int hopCount = 0;
 *     string destAddr;              // L3Address come string
 *     uint32_t destSeqNum;
 *     string originatorAddr;        // L3Address come string
 *     simtime_t lifeTime;
 * 
 *     // ECDSA security fields
 *     string senderId;
 *     uint64_t timestamp;
 *     uint32_t nonce;
 *     string signature;
 * }
 * </pre>
 */
class Rrep : public ::networkprojectvanet::replay::replay_mitigation_ecdsa::AodvControlPacket
{
  protected:
    bool repairFlag = false;
    bool ackRequiredFlag = false;
    unsigned int prefixSize = 0;
    unsigned int hopCount = 0;
    omnetpp::opp_string destAddr;
    uint32_t destSeqNum = 0;
    omnetpp::opp_string originatorAddr;
    omnetpp::simtime_t lifeTime = SIMTIME_ZERO;
    omnetpp::opp_string senderId;
    uint64_t timestamp = 0;
    uint32_t nonce = 0;
    omnetpp::opp_string signature;

  private:
    void copy(const Rrep& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Rrep&);

  public:
    Rrep(const char *name=nullptr, short kind=0);
    Rrep(const Rrep& other);
    virtual ~Rrep();
    Rrep& operator=(const Rrep& other);
    virtual Rrep *dup() const override {return new Rrep(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getRepairFlag() const;
    virtual void setRepairFlag(bool repairFlag);
    virtual bool getAckRequiredFlag() const;
    virtual void setAckRequiredFlag(bool ackRequiredFlag);
    virtual unsigned int getPrefixSize() const;
    virtual void setPrefixSize(unsigned int prefixSize);
    virtual unsigned int getHopCount() const;
    virtual void setHopCount(unsigned int hopCount);
    virtual const char * getDestAddr() const;
    virtual void setDestAddr(const char * destAddr);
    virtual uint32_t getDestSeqNum() const;
    virtual void setDestSeqNum(uint32_t destSeqNum);
    virtual const char * getOriginatorAddr() const;
    virtual void setOriginatorAddr(const char * originatorAddr);
    virtual omnetpp::simtime_t getLifeTime() const;
    virtual void setLifeTime(omnetpp::simtime_t lifeTime);
    virtual const char * getSenderId() const;
    virtual void setSenderId(const char * senderId);
    virtual uint64_t getTimestamp() const;
    virtual void setTimestamp(uint64_t timestamp);
    virtual uint32_t getNonce() const;
    virtual void setNonce(uint32_t nonce);
    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rrep& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rrep& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg:79</tt> by nedtool.
 * <pre>
 * //
 * // RERR (minimal, no ECDSA)
 * //
 * packet Rerr extends AodvControlPacket
 * {
 *     packetType = RERR;
 *     bool noDeleteFlag = false;
 *     unsigned int destCount = 0;
 *     string unreachableNodes[];
 *     uint32_t unreachableSeqNums[];
 * }
 * </pre>
 */
class Rerr : public ::networkprojectvanet::replay::replay_mitigation_ecdsa::AodvControlPacket
{
  protected:
    bool noDeleteFlag = false;
    unsigned int destCount = 0;
    omnetpp::opp_string *unreachableNodes = nullptr;
    size_t unreachableNodes_arraysize = 0;
    uint32_t *unreachableSeqNums = nullptr;
    size_t unreachableSeqNums_arraysize = 0;

  private:
    void copy(const Rerr& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Rerr&);

  public:
    Rerr(const char *name=nullptr, short kind=0);
    Rerr(const Rerr& other);
    virtual ~Rerr();
    Rerr& operator=(const Rerr& other);
    virtual Rerr *dup() const override {return new Rerr(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getNoDeleteFlag() const;
    virtual void setNoDeleteFlag(bool noDeleteFlag);
    virtual unsigned int getDestCount() const;
    virtual void setDestCount(unsigned int destCount);
    virtual void setUnreachableNodesArraySize(size_t size);
    virtual size_t getUnreachableNodesArraySize() const;
    virtual const char * getUnreachableNodes(size_t k) const;
    virtual void setUnreachableNodes(size_t k, const char * unreachableNodes);
    virtual void insertUnreachableNodes(const char * unreachableNodes);
    virtual void insertUnreachableNodes(size_t k, const char * unreachableNodes);
    virtual void eraseUnreachableNodes(size_t k);
    virtual void setUnreachableSeqNumsArraySize(size_t size);
    virtual size_t getUnreachableSeqNumsArraySize() const;
    virtual uint32_t getUnreachableSeqNums(size_t k) const;
    virtual void setUnreachableSeqNums(size_t k, uint32_t unreachableSeqNums);
    virtual void insertUnreachableSeqNums(uint32_t unreachableSeqNums);
    virtual void insertUnreachableSeqNums(size_t k, uint32_t unreachableSeqNums);
    virtual void eraseUnreachableSeqNums(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Rerr& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Rerr& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>replay/replay_mitigation_ecdsa/messages/EcdsaAodvControlPackets.msg:91</tt> by nedtool.
 * <pre>
 * //
 * // RREPACK (minimal, no ECDSA)
 * //
 * packet RrepAck extends AodvControlPacket
 * {
 *     packetType = RREPACK;
 * }
 * </pre>
 */
class RrepAck : public ::networkprojectvanet::replay::replay_mitigation_ecdsa::AodvControlPacket
{
  protected:

  private:
    void copy(const RrepAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RrepAck&);

  public:
    RrepAck(const char *name=nullptr, short kind=0);
    RrepAck(const RrepAck& other);
    virtual ~RrepAck();
    RrepAck& operator=(const RrepAck& other);
    virtual RrepAck *dup() const override {return new RrepAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RrepAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RrepAck& obj) {obj.parsimUnpack(b);}

} // namespace replay_mitigation_ecdsa
} // namespace replay
} // namespace networkprojectvanet

#endif // ifndef __NETWORKPROJECTVANET__REPLAY__REPLAY_MITIGATION_ECDSA_ECDSAAODVCONTROLPACKETS_M_H

