//
// Generated file, do not edit! Created by nedtool 5.6 from grayhole/grayhole_mitigation/messages/IntermediateAck_m.msg.
//

#ifndef __INTERMEDIATEACK_M_M_H
#define __INTERMEDIATEACK_M_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class IntermediateAck;
// cplusplus {{
#include "inet/common/INETDefs.h"
// }}

/**
 * Class generated from <tt>grayhole/grayhole_mitigation/messages/IntermediateAck_m.msg:9</tt> by nedtool.
 * <pre>
 * packet IntermediateAck
 * {
 *     int originalPacketId;   // ID del pacchetto dati originale
 *     bool mic;                // MIC=1 ACK legittimo, MIC=0 ACK falso (drop)
 *     int senderNodeId;       // Chi invia questo ACK
 *     int previousHopNodeId;  // A chi propagare l'ACK (predecessore nel path)
 *     double timestamp;          // Timestamp di creazione (per log/debug)
 * }
 * </pre>
 */
class IntermediateAck : public ::omnetpp::cPacket
{
  protected:
    int originalPacketId = 0;
    bool mic = false;
    int senderNodeId = 0;
    int previousHopNodeId = 0;
    double timestamp = 0;

  private:
    void copy(const IntermediateAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IntermediateAck&);

  public:
    IntermediateAck(const char *name=nullptr, short kind=0);
    IntermediateAck(const IntermediateAck& other);
    virtual ~IntermediateAck();
    IntermediateAck& operator=(const IntermediateAck& other);
    virtual IntermediateAck *dup() const override {return new IntermediateAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getOriginalPacketId() const;
    virtual void setOriginalPacketId(int originalPacketId);
    virtual bool getMic() const;
    virtual void setMic(bool mic);
    virtual int getSenderNodeId() const;
    virtual void setSenderNodeId(int senderNodeId);
    virtual int getPreviousHopNodeId() const;
    virtual void setPreviousHopNodeId(int previousHopNodeId);
    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IntermediateAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IntermediateAck& obj) {obj.parsimUnpack(b);}

#endif // ifndef __INTERMEDIATEACK_M_M_H

