//
// Generated file, do not edit! Created by nedtool 5.6 from grayhole/grayhole_mitigation/messages/TrustBeacon.msg.
//

#ifndef __TRUSTBEACON_M_H
#define __TRUSTBEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class TrustBeacon;
/**
 * Class generated from <tt>grayhole/grayhole_mitigation/messages/TrustBeacon.msg:1</tt> by nedtool.
 * <pre>
 * message TrustBeacon
 * {
 *     int senderNodeId;
 * 
 *     int aboutNodeId;
 * 
 *     double trustValue;
 * 
 * }
 * </pre>
 */
class TrustBeacon : public ::omnetpp::cMessage
{
  protected:
    int senderNodeId = 0;
    int aboutNodeId = 0;
    double trustValue = 0;

  private:
    void copy(const TrustBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TrustBeacon&);

  public:
    TrustBeacon(const char *name=nullptr, short kind=0);
    TrustBeacon(const TrustBeacon& other);
    virtual ~TrustBeacon();
    TrustBeacon& operator=(const TrustBeacon& other);
    virtual TrustBeacon *dup() const override {return new TrustBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSenderNodeId() const;
    virtual void setSenderNodeId(int senderNodeId);
    virtual int getAboutNodeId() const;
    virtual void setAboutNodeId(int aboutNodeId);
    virtual double getTrustValue() const;
    virtual void setTrustValue(double trustValue);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TrustBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TrustBeacon& obj) {obj.parsimUnpack(b);}

#endif // ifndef __TRUSTBEACON_M_H

